---


keepalived_vrrp_192_168_99_84_r70:
  name: keepalived_vrrp_192_168_99_84_r70
  id: 84
  ip: 192.168.99.84/24
  track_script: chk_sphinx  #chk_nginx # chk_bind9
  password: 9984

  keepalived_server_list:
 
  #deli2
  - ip_management: deli2.dev.rugion.ru
    keepalived_vrrp_dev: p5p1
    keepalived_vrrp_role: BACKUP
    keepalived_vrrp_priority: 20
    dont_make_script_check: yes

  #bkk
  - ip_management: bkk.dev.rugion.ru
    keepalived_vrrp_dev: eth0
    keepalived_vrrp_role: MASTER
    keepalived_vrrp_priority: 40
    dont_make_script_check: yes


