---

keepalived_vrrp_19:
  name: VI_19
  id: 19
  ip: 195.226.222.19/24 
  track_script: chk_bind9  #chk_nginx # chk_bind9
  password: 2219

  keepalived_server_list:
  - ip_management: 10.20.16.12
    keepalived_vrrp_dev: bond0.200
    keepalived_vrrp_role: BACKUP
    keepalived_vrrp_priority: 20
    dont_make_script_check: yes

  - ip_management: 10.20.16.11
    keepalived_vrrp_dev: bond0.200
    keepalived_vrrp_role: MASTER
    keepalived_vrrp_priority: 40
