version: '2'
services:

##
## we are using nginx that runs on kenny
##
###  nginx:
##    image: nginx:1.10
##    ports:
##      - 80:80
##    volumes:
##       - ./conf/nginx:/etc/nginx/conf.d/:ro
##    networks:
##      - registry-net
##    depends_on:
##      - registry
##      - registry-web

  registry-web:
    image: hyper/docker-registry-web:latest
    ports:
      - 8082:8080
    volumes:
       - ./conf/registry-web:/conf:ro
       - ./db:/data
    depends_on:
       - registry
    container_name: registry_web

  registry:
    image: registry:2.4.1
    ports:
      - 5000:5000
    volumes:
      - ./conf/registry:/etc/docker/registry:ro
      - /mnt/volumes/docker-registry/data:/var/lib/registry
    container_name: registry

